# Copyright (c) 2020 Ryan Cross
# SPDX-License-Identifier: MIT

# Uncomment to enable ZMK_STUDIO support
CONFIG_ZMK_STUDIO=y

# Uncommetn to enable mouse movement
CONFIG_ZMK_POINTING=y

# Uncomment to enable sleep
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=7200000

# Uncomment the line below to disable external power toggling by the underglow.
# By default toggling the underglow on and off also toggles external power
# on and off. This also causes the display to turn off.
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
CONFIG_ZMK_STUDIO_LOCKING=n

# Uncomment the following line to enable the Sofle OLED Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
CONFIG_ZMK_WIDGET_WPM_STATUS=n

# Uncomment these two lines to add support for encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Uncomment this line below to add rgb underglow / backlight support
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=10
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=25

# Improved antenna power
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Custom display shenanigans
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_SMART_BATTERY=y
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CAT=n
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_SPACEMAN=y
CONFIG_NICE_OLED_WIDGET_RAW_HID=y

# Naming
CONFIG_ZMK_KEYBOARD_NAME="SHADOSOFLE"
